openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/user/login:
    post:
      summary: 'User LogIn'
      operationId: userLogIn
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  token: 'generate token'
                properties:
                  token:
                    type: string
                    example: 'generate token'
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ''
                  example: bauch.tyree@example.net
                password:
                  type: string
                  description: ''
                  example: 'C<J6+d":yx@W[Kcr'
                device_name:
                  type: string
                  description: "To identified user login devices. Won't be needed for web."
                  example: dolorem
              required:
                - email
                - password
      security: []
  /api/user/register:
    post:
      summary: 'User Register'
      operationId: userRegister
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  id: 1
                  name: ab
                  email: admin@gmail.com
                  phone: temporibus
                  age: 18
                  device_name: Iphone
                  degree: commodi
                  job_title: 'Team Lead at google'
                  bio: 'Awesome developer'
                  updated_at: '2023-05-29:16:06:33'
                  created_at: '2023-05-29:16:06:33'
                  token: 1|qo6eJceg77saTfqEl6bJ5SJ8J38uUEgIwgxHYX7m
                  profile_photo_path: path/to/profile_image
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: ab
                  email:
                    type: string
                    example: admin@gmail.com
                  phone:
                    type: string
                    example: temporibus
                  age:
                    type: integer
                    example: 18
                  device_name:
                    type: string
                    example: Iphone
                  degree:
                    type: string
                    example: commodi
                  job_title:
                    type: string
                    example: 'Team Lead at google'
                  bio:
                    type: string
                    example: 'Awesome developer'
                  updated_at:
                    type: string
                    example: '2023-05-29:16:06:33'
                  created_at:
                    type: string
                    example: '2023-05-29:16:06:33'
                  token:
                    type: string
                    example: 1|qo6eJceg77saTfqEl6bJ5SJ8J38uUEgIwgxHYX7m
                  profile_photo_path:
                    type: string
                    example: path/to/profile_image
      tags:
        - Auth
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: odit
                profile_photo:
                  type: 'max:2048kb'
                  description: ''
                  example: ut
                email:
                  type: string
                  description: 'Must Be Unique'
                  example: janet07@example.net
                phone:
                  type: string
                  description: ''
                  example: ipsum
                age:
                  type: integer
                  description: 'min:16'
                  example: 18
                degree:
                  type: string
                  description: ''
                  example: aut
                'job_title ':
                  type: string
                  description: ''
                  example: consequatur
                device_name:
                  type: string
                  description: ''
                  example: quod
                bio:
                  type: string
                  description: ''
                  example: consequatur
                password:
                  type: string
                  description: 'min:8|confirmed'
                  example: '*~0//f;B2@d-0C8'
                password_confirmation:
                  type: required
                  description: min8
                  example: ducimus
                job_title:
                  type: string
                  description: ''
                  example: id
              required:
                - name
                - email
                - phone
                - password
      security: []
  /api/topic:
    get:
      summary: 'Topic listing'
      operationId: topicListing
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {ACCESS_TOKEN}'
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Topics
tags:
  -
    name: Auth
    description: ''
  -
    name: Topics
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
